### ISSUE TITLE
Incompatible with JAVA16

### ISSUE THREAD

**Issue by somesh-pal-by** [Azure/azure-data-lake-store-java#49]
Create Directory throws below error:

Java: 16

**java.lang.IllegalStateException: javax.security.cert.CertificateException: Could not find class: java.lang.ClassNotFoundException: com/sun/security/cert/internal/x509/X509V1CertImpl**
        at org.wildfly.openssl.OpenSSlSession.initPeerCertChain(OpenSSlSession.java:285) ~[wildfly-openssl-1.0.7.Final.jar:1.0.7.Final]
        at org.wildfly.openssl.OpenSSlSession.initialised(OpenSSlSession.java:295) ~[wildfly-openssl-1.0.7.Final.jar:1.0.7.Final]
        at org.wildfly.openssl.OpenSSLSessionContext.clientSessionCreated(OpenSSLSessionContext.java:132) ~[wildfly-openssl-1.0.7.Final.jar:1.0.7.Final]
        at org.wildfly.openssl.OpenSSLClientSessionContext.storeClientSideSession(OpenSSLClientSessionContext.java:94) ~[wildfly-openssl-1.0.7.Final.jar:1.0.7.Final]
        at org.wildfly.openssl.OpenSSLEngine.handshakeFinished(OpenSSLEngine.java:1016) ~[wildfly-openssl-1.0.7.Final.jar:1.0.7.Final]
        at org.wildfly.openssl.OpenSSLEngine.getHandshakeStatus(OpenSSLEngine.java:1065) ~[wildfly-openssl-1.0.7.Final.jar:1.0.7.Final]
        at org.wildfly.openssl.OpenSSLEngine.unwrap(OpenSSLEngine.java:654) ~[wildfly-openssl-1.0.7.Final.jar:1.0.7.Final]
        at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679) ~[na:na]
        at org.wildfly.openssl.OpenSSLSocket.runHandshake(OpenSSLSocket.java:324) ~[wildfly-openssl-1.0.7.Final.jar:1.0.7.Final]
        at org.wildfly.openssl.OpenSSLSocket.startHandshake(OpenSSLSocket.java:210) ~[wildfly-openssl-1.0.7.Final.jar:1.0.7.Final]
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:574) ~[na:na]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1419) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1390) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220) ~[na:na]
        at com.microsoft.azure.datalake.store.HttpTransport.makeSingleCall(HttpTransport.java:293) ~[azure-data-lake-store-sdk-2.3.9.jar:2.3.9]
        at com.microsoft.azure.datalake.store.HttpTransport.makeCall(HttpTransport.java:90) ~[azure-data-lake-store-sdk-2.3.9.jar:2.3.9]
        at com.microsoft.azure.datalake.store.Core.mkdirs(Core.java:440) ~[azure-data-lake-store-sdk-2.3.9.jar:2.3.9]
        at com.microsoft.azure.datalake.store.ADLStoreClient.createDirectory(ADLStoreClient.java:665) ~[azure-data-lake-store-sdk-2.3.9.jar:2.3.9]

**Comment by ziedayadisg** [comment]
Is there any updates ? I'm facing the same issue

**Comment by snvijaya** [comment]
Hi @ziedayadisg  , Can you please share which team you are part of ? As Azure Storage Gen1 has been retired, this SDK is not supported anymore.
