### ISSUE TITLE
AdlFileSystem: Set Owner failed with  failed with error 0x83090aa2

### ISSUE THREAD

**Issue by JDatta** [Azure/azure-data-lake-store-java#5]
I am trying to create a directory in Azure Data Lake and then set the owner attribute. I am using the following code to achieve this:

```java
    Configuration conf = new Configuration();
    conf.addResource(new Path("/path/to/core-site.xml"));

    Path path =
      new Path("adl://accountname.azuredatalakestore.net/path/to/directory");

    AdlFileSystem fs = (AdlFileSystem) FileSystem.get(path.toUri(), conf);
    fs.mkdirs(path);  // SUCCEEDS

    FileStatus status = fs.getFileStatus(path); // SUCCEEDS

    fs.setOwner(path, status.getOwner(), status.getGroup()); // FAILS!
```

The `fs.setOwner(...)` call above fails with the following exception even though the same owner and group parameters passed as received from the `fs.getFileStatus(path)` call.

```
Exception in thread "main" org.apache.hadoop.security.AccessControlException: Set Owner failed with  failed with error 0x83090aa2 (Forbidden. ACL verification failed. Either the resource does not exist or the user is not authorized to perform the requested operation.). [715f4073-8615-4a6f-8bd0-bbcb2b3cd767][2017-08-29T03:13:51.5592332-07:00] [ServerRequestId:715f4073-8615-4a6f-8bd0-bbcb2b3cd767]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.microsoft.azure.datalake.store.ADLStoreClient.getRemoteException(ADLStoreClient.java:1167)
	at com.microsoft.azure.datalake.store.ADLStoreClient.getExceptionFromResponse(ADLStoreClient.java:1132)
	at com.microsoft.azure.datalake.store.ADLStoreClient.setOwner(ADLStoreClient.java:756)
	at org.apache.hadoop.fs.adl.AdlFileSystem.setOwner(AdlFileSystem.java:649)
       [...]
```
Can you please suggest what could be the issue. I need to set the owner field using ADL FileSystem JAVA APIs.

**Comment by yagupta** [comment]
In Azure Data Lake Store ( & in HDFS) only the super-user of the account can change the owner of a file/folder. Hope this helps.

**Comment by JDatta** [comment]
I have tried the following things and it all fails.
  - Tried with the object id of the "owner" of the object (it is a service principle in Azure AD). I think this should be the owning user as per documentation.
  - Tried with the owner of the resource group; that too fails. I think this should be the super user; 

According to documentation <https://docs.microsoft.com/en-us/azure/data-lake-store/data-lake-store-access-control>, both of the should have the permission to set owner.

**Comment by JDatta** [comment]
While connecting I was using the service principle of the owning user

**Comment by asikaria-msft** [comment]
Not sure if this was resolved, but file ownership can only be changed by the account owner, not by the owner of the file or directory. So the service principal in core-site above must be owner of the account. To confirm owner, open the Data Lake store account in the portal (portal.azure.com), and click on "Access Control (IAM)". Your service principal should show up on the list, and the role should say "Owner".

Setting the service principal as owner of resource group is insufficient, if the resource itself (the ADLS account) does not have the service principal as the owner.

I am closing this issue since it has been a while, please reactivate if this does not resolve the problem.
